[wokwi]
version = 1
firmware = '../.pio/build/Esp32_WOKWI/firmware.bin'
elf = '../.wokwi/flasher_args.json'
gdbServerPort=3333
rfc2217ServerPort = 4000

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"